### ISSUE TITLE
Function getGEO

### ISSUE THREAD

**Issue by SammBS** [seandavi/GEOquery#141] opened 2023-05-06 19:13 UTC
**Describe the bug**
o comando getGEO está com erro.

Install:
BiocManager::install(version = "3.17")
BiocManager::install("GEOquery", force = TRUE)

ERRO
library(GEOquery): 
Error: package or namespace load failed for ‘GEOquery’ in get(Info[i, 1], envir = env):
 cannot open file 'C:/Users/Samara/AppData/Local/R/win-library/4.3/data.table/R/data.table.rdb': No such file or directory

**To Reproduce**
Steps to reproduce the behavior including code example:
data = getGEO(filename=system.file
+                ("GDS4550_full.soft.gz",
+                  package="GEOquery"))
```
Code example
## or
gds <- getGEO("GDS507")

**Output of Session Info:**

Error in getGEO(filename = system.file("GDS4550_full.soft.gz", package = "GEOquery")) : 
  could not find function "getGEO"
```
Cut-and-paste output of sessionInfo
```
![getGEO](https://user-images.githubusercontent.com/132780629/236642372-8ef08712-de0c-4166-b968-b8b3385a6539.JPG)

**Comment by seandavi** [comment] 2023-07-04 19:54
Hi, @SammBS. I'm not able to reproduce this error myself, so I'm going to close this. If you have further questions, consider asking on the https://support.bioconductor.org/.

**Closed by seandavi** 2023-07-04 19:54 UTC
